### ISSUE TITLE
Image info should only show when image transition has finished

### ISSUE THREAD

**Issue by sapnho** [helgeerbe/picframe#45] opened 2021-02-28 19:09 UTC
I have set fade time to 10, and transitions to every 20 sec. Immediately when crossfading starts, the info of the new photo is shown, long before the new one is properly visible. Can we only show this information when the fade-in has been completed?

Paddy had fixed that in the old version.

**Comment by sapnho** [comment] 2021-02-28 19:33
Maybe we can link this to the darkening. The background darkening only appears when the new image has fully appeared.

**Comment by paddywwoof** [comment] 2021-02-28 22:06
I can't reproduce this. I have ```show_text_tm: 8.0```, ```time_delay: 20.0```,  ```fade_time: 10.0``` but I'm running on laptop. If I use the next button the name flashes up straight away then fades out and int and out again. (Which is a bit odd but actually quite useful) Do you think it is related to the size of the images, which could be making the FPS drop? Do you get the same effect with longer time_delay or shorter fade_time?

**Comment by sapnho** [comment] 2021-03-01 08:36
My files are all 1920 x 1200px, about 2-3MB, so nothing major. But I will check different fade times when the database is updated. Currently, I can't even start anymore because of missing files links..

**Comment by helgeerbe** [comment] 2021-03-01 09:51
I have seen, that Jeff merged a partial fix to the database issue. I will create a new package, so you can test this and the dB issue.

**Comment by sapnho** [comment] 2021-03-01 12:04
I just installed the latest version, and now it works as Paddy described.

**Comment by jgodfrey** [comment] 2021-03-01 14:24
> I just installed the latest version, and now it works as Paddy described.

That's expected - until we appropriately handles missing images while the slideshow is running.

**Comment by paddywwoof** [comment] 2021-03-02 19:58
This should be fixed now in dev branch. Re-open it if the problem suddenly appears again.

**Closed by paddywwoof** 2021-03-02 19:58 UTC
